### PR TITLE
Revert miniz and support using QtZlib (aka plain libz) on windows

### PR DESCRIPTION
**Pull request by sletta**
This reverts commit 09185a385db4ce16ae123e9e72c20727315eaf0b.

### CODE REVIEW

**Comment by gladhorn** [comment]
Nice, is this going to build on Windows though?

**Review by gladhorn — APPROVED** [review]

**Comment by sletta** [comment]
Good question, will give windoze a spin

**Comment by gladhorn** [comment]
(I'm all for this change, it's just that we need to find out how to make this work on windows first I guess.)

**Comment by sletta** [comment]
Mm, and of  course it doesn't work there..

**Pull request merged**
